### ISSUE TITLE
我的微博 小部件出现问题

### ISSUE THREAD

**Issue by FelixXiong** [pengloo53/Hexo-theme-light_cn#7]
以下是代码报错：
```
/Users/felixxiong/FelixXiongHexoFolder/themes/light/layout/_widget/weibo.ejs:4
    2|   <h3 class="title">我的微博</h3>
    3|     <ul class="weibo">
 >> 4| 	<iframe width="100%" height="<%= theme.weibo.height%>" class="share_self"  frameborder="0" scrolling="no" src="<%- theme.weibo.url %>"></iframe>
    5|     </ul>
    6| </div>

Cannot read property 'height' of undefined
    at eval (eval at compile (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:584:12), <anonymous>:11:38)
    at returnedFn (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:615:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:584:12), <anonymous>:12:17)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:584:12), <anonymous>:9:22)
    at returnedFn (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:615:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:48:23)
    at fragment_cache (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/plugins/helper/partial.js:36:52)
    at Object.fragmentCache (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/plugins/helper/fragment_cache.js:9:32)
    at Object.wrapper [as fragment_cache] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/lodash/lodash.js:4941:19)
    at Object.partial (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/plugins/helper/partial.js:36:17)
    at Object.wrapper [as partial] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:584:12), <anonymous>:18:17)
    at returnedFn (/Users/felixxiong/FelixXiongHexoFolder/node_modules/ejs/lib/ejs.js:615:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/felixxiong/FelixXiongHexoFolder/node_modules/hexo/lib/theme/view.js:40:23)
```
即使设定了之后依然无法显示，设定的值为“200%”。

还有其他的小部件，我想保留国外和国内的服务，我应该如何配置里面的_widget.ejs?
是使用你这里的小部件代码加进去吗？谢谢

**Comment by FelixXiong** [comment]
@pengloo53 尝试这么做了，不知道是不是我的设置有问题，没有出现。
![](https://i.loli.net/2018/05/03/5aea58a7c61d1.png)

一些cn的代码应该和light不冲突吧？代码合并的话会好吗？
